name: Test and Deploy Training and/or Inference Images

on:
  push:
    branches:
      - main

jobs:
  # Run tests first
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest tests/

  # Build and deploy inference image (if changes are made)
  build-and-push-inference:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in 'inference/' folder
        id: changes
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch --unshallow
          fi
          
          if git diff --quiet HEAD~1 -- ./inference; then
            echo "No changes in inference/ folder."
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected in inference/ folder."
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Log in to DockerHub
        if: env.changes_detected == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: env.changes_detected == 'true'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/occupancy_inference:latest ./inference

      - name: Push Docker image
        if: env.changes_detected == 'true'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/occupancy_inference:latest


  # Build and deploy training image (if changes are made)
  build-and-push-training:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in 'training/' folder
        id: changes
        run: |
          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch --unshallow
          fi
          
          if git diff --quiet HEAD~1 -- ./training; then
            echo "No changes in training/ folder."
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected in training/ folder."
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Log in to DockerHub
        if: env.changes_detected == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: env.changes_detected == 'true'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/occupancy_training:latest ./training

      - name: Push Docker image
        if: env.changes_detected == 'true'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/occupancy_training:latest
